#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/common.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_test.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_fail.bash

cd "$(dirname "$0")"

vecho_location

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=ref at-dd-is-not-empty-fail-01.xsd

test_exit
