#!/usr/bin/env bash

cd "$(dirname "$0")"

. ../../../lib/common.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_test.bash

test_set_stdout <<EOF
12:successful-report:is-ctas-conformant-document
12:successful-report:is-schema-doc
12:successful-report:ns-valid
12:successful-report:ns-well-formed
12:successful-report:target-ns-is-rfc3986
12:successful-report:well-formed-xml
22:failed-assert:ccc-base-has-cc
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=ext -c fail1-xml-catalog.xml ns1.xsd







