#!/usr/bin/env bash



. "$(dirname "$0")"/../../../lib/common.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_test.bash

cd "$(dirname "$0")"

test_set_stdout <<EOF
2:successful-report:is-ctas-conformant-document
2:successful-report:is-schema-doc
2:successful-report:ns-valid
2:successful-report:target-ns-is-rfc3986
2:successful-report:well-formed-xml
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=ref ok.xsd

test_set_stdout <<EOF
2:successful-report:is-ctas-conformant-document
2:successful-report:is-schema-doc
2:successful-report:ns-valid
2:successful-report:target-ns-is-rfc3986
2:successful-report:well-formed-xml
60:failed-assert:rule-ct-sc-has-soag
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=ref no-soag.xsd







