#!/usr/bin/env bash

cd "$(dirname "$0")"

. ../../../lib/common.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_test.bash

test_set_stdout <<EOF
2:successful-report:is-ctas-conformant-document
2:successful-report:is-schema-doc
2:successful-report:ns-valid
2:successful-report:ns-well-formed
2:successful-report:target-ns-is-rfc3986
2:successful-report:well-formed-xml
9:failed-assert:augmentable-type-has-aug-point
9:failed-assert:object-with-cc-derived-from-object
14:failed-assert:rule-type-derived-from-augmentation-type
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=ref -c fail1-xml-catalog.xml fail1-jxdm.xsd

test_exit





