#!/usr/bin/env bash

cd "$(dirname "$0")"

. ../../../lib/common.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_test.bash

test_set_stdout <<EOF
3:successful-report:is-ctas-conformant-document
3:successful-report:is-schema-doc
3:successful-report:ns-valid
3:successful-report:target-ns-is-rfc3986
3:successful-report:well-formed-xml
14:failed-assert:rule-adapter-type-structure
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=ref -c fail1-xml-catalog.xml fail1-edxl-cap.xsd







