#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/fn_test.bash
test_process_args "$@"

cd "$NDR_TOOLS_COMMAND_DIR"
 
test_set_stdout <<EOF
9:successful-report:is-ctas-conformant-document
9:successful-report:is-schema-doc
9:successful-report:ns-valid
9:successful-report:ns-well-formed
9:successful-report:target-ns-is-rfc3986
9:successful-report:well-formed-xml
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref ok2.xsd

test_set_stdout <<EOF
9:successful-report:is-ctas-conformant-document
9:successful-report:is-schema-doc
9:successful-report:ns-valid
9:successful-report:ns-well-formed
9:successful-report:target-ns-is-rfc3986
9:successful-report:well-formed-xml
28:failed-assert:aug-type-base
28:failed-assert:rule-augmentation-type-derived-from-augmentation-type
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref bad1.xsd

test_exit


