#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/fn_test.bash
test_process_args "$@"

cd "$NDR_TOOLS_COMMAND_DIR"
# Test Rule 10-69 Deprecated annotates schema component
test_set_stdout <<EOF
13:successful-report:is-ctas-conformant-document
13:successful-report:well-formed-xml
13:successful-report:ns-well-formed
13:successful-report:ns-valid
13:successful-report:is-schema-doc
13:successful-report:target-ns-is-rfc3986
EOF


test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ext -c xml-catalog.xml MyPersonContactAssociation.xsd

test_exit


