#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/fn_test.bash
test_process_args "$@"

cd "$NDR_TOOLS_COMMAND_DIR"

test_set_stdout <<EOF
8:successful-report:is-ctas-conformant-document
8:successful-report:is-schema-doc
8:successful-report:ns-valid
8:successful-report:ns-well-formed
8:successful-report:target-ns-is-rfc3986
8:successful-report:well-formed-xml
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref ok.xsd

test_set_stdout <<EOF
8:successful-report:is-ctas-conformant-document
8:successful-report:is-schema-doc
8:successful-report:ns-valid
8:successful-report:ns-well-formed
8:successful-report:target-ns-is-rfc3986
8:successful-report:well-formed-xml
19:failed-assert:augmentable-type-has-aug-point
38:failed-assert:augmentable-type-has-aug-point
45:failed-assert:aug-el-in-type
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref bad1.xsd

test_set_stdout <<EOF
8:successful-report:is-ctas-conformant-document
8:successful-report:is-schema-doc
8:successful-report:ns-valid
8:successful-report:ns-well-formed
8:successful-report:target-ns-is-rfc3986
8:successful-report:well-formed-xml
19:failed-assert:augmentable-type-has-aug-point
26:failed-assert:aug-ref-is-last
47:failed-assert:aug-ref-is-last
47:failed-assert:aug-el-in-type
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref bad2.xsd
test_set_stdout <<EOF
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref invalid1.xsd


test_exit


