#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/common.bash
. "$NDR_TOOLS_ROOT_DIR"/lib/fn_test.bash

cd "$(dirname "$0")"

test_set_stdout <<EOF
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=set --xml-catalog=ok-xml-catalog.xml ok-niem-core.xsd

test_set_stdout <<EOF
143:failed-assert:appliestotypes-refs-types
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report --rules=set --xml-catalog=appliestotypes-contains-element-xml-catalog.xml appliestotypes-contains-element.xsd

test_exit
