#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/fn_test.bash
test_process_args "$@"

cd "$NDR_TOOLS_COMMAND_DIR"

# Test Rule 10-71 Applies to types indicates elements

test_set_stdout <<EOF
8:successful-report:is-ctas-conformant-document
8:successful-report:well-formed-xml
8:successful-report:ns-well-formed
8:successful-report:ns-valid
8:successful-report:is-schema-doc
8:successful-report:target-ns-is-rfc3986
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ext -c xml-catalog.xml metadata.xsd

# Test Rule 10-71 Applies to types indicates elements
# This should fail, because the appliesToTypes does NOT resolve to a type. But is doesn't ?!
test_set_stdout <<EOF
8:successful-report:is-ctas-conformant-document
8:successful-report:well-formed-xml
8:successful-report:ns-well-formed
8:successful-report:ns-valid
8:successful-report:is-schema-doc
8:successful-report:target-ns-is-rfc3986
18:failed-assert:appliestotypes-refs-types
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ext -c xml-catalog.xml metadataInvalid2.xsd

test_exit


