#!/usr/bin/env bash

. "$(dirname "$0")"/../../../lib/fn_test.bash
test_process_args "$@"

cd "$NDR_TOOLS_COMMAND_DIR"

test_set_stdout <<EOF
11:successful-report:is-ctas-conformant-document
11:successful-report:is-schema-doc
11:successful-report:ns-valid
11:successful-report:target-ns-is-rfc3986
11:successful-report:well-formed-xml
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref ok.xsd

test_set_stdout <<EOF
12:successful-report:is-ctas-conformant-document
12:successful-report:is-schema-doc
12:successful-report:ns-valid
12:successful-report:target-ns-is-rfc3986
12:successful-report:well-formed-xml
26:failed-assert:augmentable-type-has-aug-point
31:failed-assert:rule-ref-ccc-base-has-cc
EOF

test_run "$NDR_TOOLS_ROOT_DIR"/bin/get-test-report -r ref ccc-extends-sc.xsd

test_exit
